title: Crafty critters
hero_image: images/banner.png
description: Make a cut-out style creature with python.
listed: false
pdf: false
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged     
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7 
  - title: Step 8
  - title: Step 9
    challenge: true
    completion:
      - external
