title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged      
  - title: Step 3
    challenge: true
    completion:
      - external
