title: Crafty critters
hero_image: images/banner.png
description: Make a collage-style creature with Python
listed: true
pdf: false
landing: true
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged     
  - title: Step 3
  - title: Step 4
  - title: Step 5
    completion:
      - internal
  - title: Step 6
  - title: Step 7 
  - title: Step 8 
  - title: Step 9
    challenge: true
    completion:
      - external
